version: '3'

services:
  nexus:
    image: sonatype/nexus3:latest
    container_name: nexus
    ports:
      - "8081:8081"
      - "8082:8082"  # Pour le repo Docker (optionnel)
    volumes:
      - nexus-data:/nexus-data
    environment:
      - INSTALL4J_ADD_VM_PARAMS=-Xms4g -Xmx4g -XX:MaxDirectMemorySize=4g
    restart: always
    networks:
      - nexus-network

  nginx-nexus:
    image: nginx:latest
    container_name: nginx-nexus
    ports:
      - "3443:3443"
    volumes:
      - ./nginx-nexus.conf:/etc/nginx/nginx.conf
      - /opt/nexus/certs:/etc/nginx/certs
    networks:
      - nexus-network
    depends_on:
      - nexus
    restart: always

networks:
  nexus-network:
    driver: bridge

volumes:
  nexus-data:
