concurrent = 1
check_interval = 0
connection_max_age = "15m0s"
shutdown_timeout = 0
 
[session_server]
  session_timeout = 1800
 
[[runners]]
  name = "runner"
  url = "https://91.134.100.150"
  id = 23
  token = "glrt-zOtkaP2z6F3S52MWUlYq_286MQpwOjMKdDozCnU6OA8.01.170r1rp00"
  token_obtained_at = 2025-05-12T07:19:53Z
  token_expires_at = 0001-01-01T00:00:00Z
  tls-ca-file = "/usr/local/share/ca-certificates/gitlab-fullchain.crt"
  executor = "shell"
  shell = "bash"
  [runners.custom_build_dir]
  [runners.cache]
    MaxUploadedArchiveSize = 0
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]