services:
  guacd:
    image: guacamole/guacd:1.6.0
    container_name: guacd
    restart: always
    volumes:
      - ./recordings:/var/lib/guacamole/recordings:rw
      - ./drive:/drive

  postgres:
    image: postgres:15
    container_name: guacamole-db
    restart: always
    environment:
      POSTGRES_DB: guacamole_db
      POSTGRES_USER: guacamole_user
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d

  guacamole:
    image: guacamole/guacamole:1.6.0
    container_name: guacamole
    restart: always
    depends_on:
      - guacd
      - postgres
    environment:
      GUACD_HOSTNAME: guacd
      POSTGRESQL_HOSTNAME: postgres
      POSTGRESQL_DATABASE: guacamole_db
      POSTGRESQL_USERNAME: guacamole_user
      POSTGRESQL_PASSWORD: ${POSTGRES_PASSWORD}
      GUACAMOLE_HOME: /guacamole-home
      RECORDING_SEARCH_PATH: /var/lib/guacamole/recordings
      TOTP_ENABLED: "true"
    volumes:
      - ./guacamole-home:/guacamole-home
      - ./recordings:/var/lib/guacamole/recordings:ro
      - ./drive:/drive
    ports:
      - "8080:8080"
