services:
  guacd:
    image: guacamole/guacd:latest
    container_name: guacd
    restart: always
    volumes:
      - ./recordings:/recordings
      - ./drive:/drive

  postgres:
    image: postgres:15
    container_name: guacamole-db
    restart: always
    environment:
      POSTGRES_DB: guacamole_db
      POSTGRES_USER: guacamole_user
      POSTGRES_PASSWORD: CMOT_DE_PASSE_FORT
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d

  guacamole:
    image: guacamole/guacamole:latest
    container_name: guacamole
    restart: always
    depends_on:
      - guacd
      - postgres
    environment:
      GUACD_HOSTNAME: guacd
      POSTGRESQL_HOSTNAME: postgres
      POSTGRESQL_DATABASE: guacamole_db
      POSTGRESQL_USER: guacamole_user
      POSTGRESQL_PASSWORD: MOT_DE_PASSE_FORT
      GUACAMOLE_HOME: /guacamole-home
    volumes:
      - ./guacamole-home:/guacamole-home
    ports:
      - "8080:8080"