global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:

  # Prometheus lui-même
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  # Machine (CPU, RAM, Disk, Network)
  - job_name: "node_exporter_vmsecu4"
    static_configs:
      - targets: ["10.100.0.114:9100"]

  - job_name: "node_exporter_vmsecu2"
    static_configs:
      - targets: ["10.100.0.166:9100"]

  - job_name: "node_exporter_vm-inventaire"
    static_configs:
      - targets: ["10.100.0.113:9100"]

  - job_name: "node_exporter_irisdev"
    static_configs:
      - targets: ["10.100.0.245:9100"]

  - job_name: "node_exporter_gitlab"
    static_configs:
      - targets: ["10.100.0.98:9100"]

  - job_name: "node_exporter_serveur_mdm"
    static_configs:
      - targets: ["10.100.0.226:9100"]

  - job_name: "node_exporter_serveur_bo"
    static_configs:
      - targets: ["10.100.0.210:9100"]

  - job_name: "node_exporter_oracle_server"
    static_configs:
      - targets: ["10.100.0.9:9100"]

  - job_name: "node_exporter_serveur_odi"
    static_configs:
      - targets: ["10.100.0.133:9100"]

  - job_name: "node_exporter_test_install_gateway"
    static_configs:
      - targets: ["10.100.0.87:9100"]

  - job_name: "node_exporter_rpa_uipath"
    static_configs:
      - targets: ["10.100.0.202:9100"]

  # Vérification UP / DOWN des dockers 

  - job_name: "docker-custom-exporter"
    static_configs:
      - targets:
          - "10.100.0.114:9101" #vmsecu4
          - "10.100.0.166:9101" #vmsecu2
          - "10.100.0.113:9101" #vm-inventaire
