# Dockerfile à adapter selon votre besoin, 
# L'ensemble des Dockerfile utilisé lors de ce projet concernant la création des runners est disponible à la racine de ce Project Github : 
# Ces derniers se nomment : 
# Dockerfile runner basique : image-runner
# Dockerfile runner cpp : image-runner-cpp
# Dockerfile runner net8.0 : image-runner-net8.0
# Dockerfile runner python : image-runner-python3
# Dockerfile runner clean : image-runner-clean
# Dockerfile image docker avec certificat : image-docker-cert
