variables:
  GIT_DEPTH: 0 # Correction du shallow clone pour SonarQube

stages:
  - test-vault
  - sonar_analysis
  - dependency-update
  - cleanup

test_vault_auth:
  stage: test-vault
  tags:
    - runner
  id_tokens:
    VAULT_ID_TOKEN:
      aud: "https://91.134.72.37:8200"
  before_script:
    - apt-get update -qq
    - apt-get install -y jq
  script:
    - echo "=== JWT Token Claims ==="
    - echo "$VAULT_ID_TOKEN" | cut -d. -f2 | base64 -d 2>/dev/null | jq . || echo "Cannot decode JWT"
    - echo "=== Test connectivité Vault ==="
    - curl -k -s "$VAULT_ADDR/v1/sys/health" || echo "Vault non accessible"
    - echo "=== Authentification Vault via JWT ==="
    - |
      VAULT_RESPONSE=$(curl -s -k -X POST \
        -H "Content-Type: application/json" \
        -d "{\"role\":\"$VAULT_ATUH_ROLE_PIPELINE\",\"jwt\":\"$VAULT_ID_TOKEN\"}" \
        "$VAULT_ADDR/v1/auth/jwt/login")
      
      VAULT_TOKEN=$(echo "$VAULT_RESPONSE" | jq -r '.auth.client_token')

      if [ -z "$VAULT_TOKEN" ] || [ "$VAULT_TOKEN" = "null" ]; then
        echo " Echec de l'authentification Vault"
        exit 1
      fi

      export VAULT_TOKEN
      echo "Authentification réussie, token Vault obtenu."
    - echo "=== Lecture du secret SonarQube depuis Vault ==="
    - |
      SECRET_REPONSE=$(curl -s -k \
        -H "X-Vault-Token: $VAULT_TOKEN" \
        "$VAULT_ADDR/v1/sonarqube/data/sonarqube")
      
      SONAR_TOKEN=$(echo "$SECRET_RESPONSE" | jq -r '.data.data.SONAR_TOKEN')
      SONAR_HOST_URL=$(echo "$SECRET_RESPONSE" | jq -r '.datat.data.SONAR_HOST_URL')

      if [ -z "$SONAR_TOKEN" ] || [ "SONAR_TOKEN" = "null" ] || [ -z "$SONAR_HOST_URL" ] || [ "$SONAR_HOST_URL" = "null" ]; then
        echo "Erreur : échec lors de la récupération du token SonarQube ou de l'URL."
        exit 1
      fi

      echo "Token SonarQube récupérée."
      echo "URL SonarQube récupérée."

      echo "SONAR_TOKEN=$SONAR_TOKEN" >> sonar_secrets.env
      echo "SONAR_HOST_URL=$SONAR_HOST_URL" >> sonar_secrets.env
      openssl enc -aes-256-cbc -salt -in sonar_secrets.env -out sonar_secrets.env.enc -pass pass:"$ENCRYPTION_KEY"
  artifacts:
    paths:
      - sonar_secrets.env

sonar_scan:
  stage: sonar_analysis
  tags:
    - runner-python3
  dependencies:
    - test_vault_auth
  before_script:
    - echo "=== Configuration pip vers Nexus ==="
    - mkdir -p ~/.pip
    - |
      cat > ~/.pip/pip.conf <<EOF
      [global]
      index-url = "https://91.134.72.37:3443/repository/python-group/simple"
      trusted-host = 91.134.72.37
      EOF
    - echo "pip cofiguré pour utiliser Nexus"
    - python3 -m venv venv
    - source venv/bin/activate
    - echo "=== Installation de coverage depuis Nexus ==="
    - pip install --no-cache-dir coverage unittest-xml-reporting
  script:
   - openssl enc -aes-256-cbc -d -in sonar_secrets.env.enc -out sonar_secrets.env -pass pass:"$ENCRYPTION_KEY"
   - source sonar_secrets.env
   - srouce venv/bin/activate
   - python -m coverage run -m unittest discover -s tests -p 'test_*.py'
   - python -m coverage xml -o coverage.xml
   - python -m coverage report
   - sonar-scanner -Dsonar.host.url="$SONAR_HOST_URL"
      -Dsonar.login="$SONAR_TOKEN"
      -Dsonar.python.coverage.reportPaths=coverage.xml
      -Dsonar.exclusions='**/site-packages/**,**/dist-packages/**,**/__pycache__/**,**/*.pyc'
      -Dsonar.inclusions='src/**/*.py,test/**/*.py'
  only:
    - main

dependabot:
  stage: dependency-update
  image: 
    name: ghcr.io/dependabot/dependabot-updater-pip:latest
    entrypoint: [""] 
  tags:
    - runner
  variables:
    NEXUS_URL: "https://91.134.72.37:3443"
    NEXUS_PYPI_INDEX: "https://91.134.72.37:3443/repository/python-group/simple"
    GITLAB_API: "https://91.134.100.150/api/v4"
    GIT_USER_NAME: "dependabot-bot"
    GIT_USER_EMAIL: "dependabot@example.com"
    BRANCH_NAME: "dependabot-updates"
    DEPENDABOT_PACKAGE_MANAGER: "pip"
    # 🔥 PRIORITÉ NUCLÉAIRE NEXUS - Blocage total de PyPI public
    PIP_INDEX_URL: "https://91.134.72.37:3443/repository/python-group/simple"
    PIP_TRUSTED_HOST: "91.134.72.37"
    PIP_NO_INDEX: "false"
    PIP_DISABLE_PIP_VERSION_CHECK: "1"
  before_script:
    - echo "⚙️ Configuration de l'environnement Dependabot"
    - apt-get update -qq && apt-get install -y git curl jq
    
    # 🔥 BLOCAGE TOTAL DE PYPI.ORG - PRIORITÉ NUCLÉAIRE NEXUS
    - echo "🚨 ACTIVATION DU MODE NEXUS PRIORITÉ ABSOLUE 🚨"
    - |
      # Suppression de toute référence à PyPI public
      mkdir -p ~/.pip
      cat > ~/.pip/pip.conf <<EOF
      [global]
      index-url = https://91.134.72.37:3443/repository/python-group/simple
      trusted-host = 91.134.72.37
      no-cache-dir = true
      disable-pip-version-check = true
      
      [install]
      trusted-host = 91.134.72.37
      EOF
      
      # Configuration pip via variables d'environnement (triple sécurité)
      export PIP_INDEX_URL="https://91.134.72.37:3443/repository/python-group/simple"
      export PIP_TRUSTED_HOST="91.134.72.37"
      export PYTHON_KEYRING_BACKEND=keyring.backends.null.Keyring
      
      # 🔒 Configuration SSL pour certificat auto-signé
      export CURL_CA_BUNDLE=""
      export REQUESTS_CA_BUNDLE=""
      export SSL_CERT_FILE=""
      pip config set global.cert ""
      
      # Vérification de la config pip
      echo "✅ Configuration pip.conf créée:"
      cat ~/.pip/pip.conf
      echo ""
      
    - git config --global user.name "$GIT_USER_NAME"
    - git config --global user.email "$GIT_USER_EMAIL"
    - git config --global --add safe.directory "$CI_PROJECT_DIR"
    
  script:
    - echo "🚀 Analyse des dépendances Python avec Dependabot (MODE NEXUS ONLY)"
    
    # 🌐 TEST DE CONNECTIVITÉ NEXUS (BLOQUANT) - Certificat auto-signé OK
    - |
      echo "🌐 Vérification CRITIQUE de la connectivité à Nexus (certificat auto-signé accepté)..."
      
      # Test de plusieurs URLs possibles pour Nexus PyPI
      NEXUS_URLS=(
        "https://91.134.72.37:3443/repository/python-group/simple"
        "https://91.134.72.37:3443/repository/python-group/simple/"
        "https://91.134.72.37:3443/repository/python-group"
        "https://91.134.72.37:3443/repository/python-group/"
      )
      
      WORKING_URL=""
      for url in "${NEXUS_URLS[@]}"; do
        echo "🔍 Test de: $url"
        HTTP_CODE=$(curl -k -s -o /dev/null -w "%{http_code}" --max-time 5 "$url")
        echo "   → HTTP $HTTP_CODE"
        
        if [ "$HTTP_CODE" = "200" ] || [ "$HTTP_CODE" = "301" ] || [ "$HTTP_CODE" = "302" ]; then
          WORKING_URL="$url"
          echo "   ✅ Cette URL fonctionne !"
          break
        fi
      done
      
      if [ -z "$WORKING_URL" ]; then
        echo ""
        echo "❌ ❌ ❌ ERREUR CRITIQUE: Aucune URL Nexus valide trouvée"
        echo ""
        echo "🔍 URLs testées:"
        for url in "${NEXUS_URLS[@]}"; do
          echo "  - $url"
        done
        echo ""
        echo "💡 Solutions possibles:"
        echo "  1. Vérifiez dans Nexus UI → Repositories → python-group → Copy URL"
        echo "  2. L'URL correcte devrait ressembler à:"
        echo "     https://91.134.72.37:3443/repository/python-group/simple"
        echo "  3. Ou sans /simple:"
        echo "     https://91.134.72.37:3443/repository/python-group"
        echo ""
        echo "🔍 Test manuel détaillé de l'URL principale:"
        curl -k -v "https://91.134.72.37:3443/repository/python-group/simple" 2>&1 | head -n 40
        exit 1
      fi
      
      echo ""
      echo "✅ ✅ ✅ Nexus est accessible via: $WORKING_URL"
      echo "🔒 Certificat auto-signé accepté avec -k/--insecure"
      
      # Mise à jour de la variable pour utiliser l'URL qui fonctionne
      export NEXUS_PYPI_INDEX="$WORKING_URL"
      export PIP_INDEX_URL="$WORKING_URL"
      pip config set global.index-url "$WORKING_URL"
      
      echo "🔧 Configuration mise à jour avec l'URL fonctionnelle"
    
    # 📦 INSTALLATION DE pip-tools DEPUIS NEXUS UNIQUEMENT
    - |
      echo "📥 Installation de pip-tools EXCLUSIVEMENT depuis Nexus (certificat auto-signé accepté)..."
      echo "🔗 Source: $NEXUS_PYPI_INDEX"
      
      # Installation avec désactivation de la vérification SSL
      pip install \
        --index-url "$NEXUS_PYPI_INDEX" \
        --trusted-host "91.134.72.37" \
        --no-cache-dir \
        --disable-pip-version-check \
        pip-tools -v 2>&1 || {
        echo "❌ ERREUR: Impossible d'installer pip-tools depuis Nexus"
        echo "🔍 Diagnostic:"
        echo "  - URL utilisée: $NEXUS_PYPI_INDEX"
        echo "  - Test curl direct du package pip-tools:"
        curl -k -s "$NEXUS_PYPI_INDEX/pip-tools/" 2>&1 | head -n 20 || echo "Package pip-tools introuvable sur Nexus"
        echo ""
        echo "💡 Vérifiez que pip-tools est bien disponible sur votre Nexus PyPI proxy/group"
        exit 1
      }
      
      echo "✅ pip-tools installé avec succès depuis Nexus"
    
    # 🔍 DÉTECTION OU CRÉATION DE requirements.txt
    - |
      echo "🔍 Recherche ou création de requirements.txt..."
      
      if [ -f "requirements.txt" ]; then
        echo "✅ requirements.txt existe déjà"
        DEPS_FILE="requirements.txt"
      else
        echo "⚠️ requirements.txt n'existe pas - CRÉATION AUTOMATIQUE"
        
        # Recherche de tous les fichiers Python
        PYTHON_FILES=$(find . -name "*.py" -not -path "*/\.*" -not -path "*/venv/*" -not -path "*/env/*")
        
        if [ -z "$PYTHON_FILES" ]; then
          echo "❌ Aucun fichier Python trouvé dans le projet"
          echo "📝 Structure du projet:"
          ls -la
          exit 0
        fi
        
        echo "🐍 Fichiers Python trouvés:"
        echo "$PYTHON_FILES"
        echo ""
        
        # Extraction des imports Python
        echo "📋 Extraction des dépendances depuis le code Python..."
        IMPORTS=$(grep -rh "^import \|^from " --include="*.py" . 2>/dev/null | \
                  sed 's/^import //; s/^from //; s/ import.*//; s/\..*//; s/ as.*//' | \
                  sort -u | \
                  grep -v "^__" | \
                  grep -v "^\." | \
                  tr '[:upper:]' '[:lower:]')
        
        if [ -z "$IMPORTS" ]; then
          echo "⚠️ Aucun import détecté - Création d'un requirements.txt minimal"
          echo "# Fichier généré automatiquement par Dependabot" > requirements.txt
          echo "# Ajoutez vos dépendances ici" >> requirements.txt
        else
          echo "📦 Imports détectés:"
          echo "$IMPORTS"
          echo ""
          
          # Création du requirements.txt avec les packages détectés
          echo "# Fichier généré automatiquement par Dependabot" > requirements.txt
          echo "# Source: Nexus PyPI ($NEXUS_PYPI_INDEX)" >> requirements.txt
          echo "# Date: $(date)" >> requirements.txt
          echo "" >> requirements.txt
          
          # Filtrage des packages standards Python (pas besoin de les installer)
          STDLIB="os sys re json time datetime collections math random string io argparse logging"
          
          for pkg in $IMPORTS; do
            # Vérifier si ce n'est pas un package standard
            if ! echo "$STDLIB" | grep -qw "$pkg"; then
              # Tentative de résolution du package sur Nexus
              echo "🔍 Recherche de $pkg sur Nexus..."
              if curl -k -s --max-time 5 "$NEXUS_PYPI_INDEX/$pkg/" 2>/dev/null | grep -qi "$pkg\|<html"; then
                echo "$pkg" >> requirements.txt
                echo "  ✅ $pkg trouvé sur Nexus"
              else
                echo "  ⚠️ $pkg non trouvé sur Nexus (ignoré)"
              fi
            fi
          done
          
          echo ""
          echo "📄 requirements.txt généré:"
          cat requirements.txt
        fi
        
        DEPS_FILE="requirements.txt"
        
        # Commit du fichier nouvellement créé
        if [ -f "requirements.txt" ] && [ -s "requirements.txt" ]; then
          git add requirements.txt
          if ! git diff --cached --quiet; then
            echo "💾 Commit du nouveau requirements.txt..."
            git checkout -B "$BRANCH_NAME"
            git commit -m "chore: création automatique de requirements.txt

            Fichier généré automatiquement par Dependabot
            Source: Nexus PyPI ($NEXUS_PYPI_INDEX)
            
            Dépendances détectées depuis le code Python du projet."
            
            git push -f "https://oauth2:${GITLAB_TOKEN}@91.134.100.150/${CI_PROJECT_PATH}.git" "$BRANCH_NAME"
            
            echo "🔀 Création de la Merge Request pour le nouveau requirements.txt..."
            MR_RESPONSE=$(curl -k -s --request POST "${GITLAB_API}/projects/${CI_PROJECT_ID}/merge_requests" \
              --header "PRIVATE-TOKEN: ${GITLAB_TOKEN}" \
              --header "Content-Type: application/json" \
              --data "{
                \"source_branch\": \"${BRANCH_NAME}\",
                \"target_branch\": \"main\",
                \"title\": \"📦 Création automatique de requirements.txt\",
                \"description\": \"Ce fichier requirements.txt a été généré automatiquement par Dependabot en analysant les imports Python du projet.\\n\\n### Source\\n- Nexus PyPI: $NEXUS_PYPI_INDEX\\n\\n**Action requise:** Vérifiez et mergez ce fichier pour activer les mises à jour automatiques.\",
                \"remove_source_branch\": true,
                \"squash\": true
              }")
            
            echo "$MR_RESPONSE" | jq -r '.web_url // "❌ Erreur lors de la création de la MR"'
            
            echo "✅ Merge Request créée - Prochain run analysera les mises à jour"
            exit 0
          fi
        fi
      fi
    
    # 🔄 ANALYSE ET MISE À JOUR DES DÉPENDANCES (MODE NEXUS ONLY)
    - |
      echo "📦 Analyse de $DEPS_FILE avec NEXUS UNIQUEMENT"
      echo "📄 Contenu actuel de $DEPS_FILE:"
      cat "$DEPS_FILE"
      echo ""
      
      # Sauvegarde
      cp "$DEPS_FILE" "${DEPS_FILE}.old"
      
      # Création du requirements.in si nécessaire
      if [ ! -f "requirements.in" ]; then
        cp "$DEPS_FILE" requirements.in
        echo "📝 requirements.in créé depuis requirements.txt"
      fi
      
      echo "🔄 Compilation avec pip-compile (SOURCE: NEXUS UNIQUEMENT)"
      echo "🔗 Index: $NEXUS_PYPI_INDEX"
      
      # Compilation avec TOUS les flags Nexus + certificat auto-signé OK
      pip-compile \
        --index-url "$NEXUS_PYPI_INDEX" \
        --trusted-host "91.134.72.37" \
        --upgrade \
        --verbose \
        --no-header \
        --allow-unsafe \
        --output-file "${DEPS_FILE}.new" \
        requirements.in 2>&1 || \
      pip-compile \
        --index-url "$NEXUS_PYPI_INDEX" \
        --trusted-host "91.134.72.37" \
        --upgrade \
        --verbose \
        --allow-unsafe \
        --output-file "${DEPS_FILE}.new" \
        "$DEPS_FILE" 2>&1 || {
          echo "⚠️ Erreur lors de la compilation"
          echo "📋 Vérifiez que tous les packages sont disponibles sur Nexus"
          echo "🔍 Packages demandés:"
          cat requirements.in 2>/dev/null || cat "$DEPS_FILE"
          exit 0
      }
      
      # Vérification des changements
      if [ -f "${DEPS_FILE}.new" ]; then
        echo ""
        echo "📄 Nouveau contenu généré depuis NEXUS:"
        cat "${DEPS_FILE}.new"
        echo ""
        
        if ! diff -q "$DEPS_FILE" "${DEPS_FILE}.old" > /dev/null 2>&1; then
          echo "📝 ✅ MISES À JOUR DÉTECTÉES depuis Nexus !"
          echo "📊 Différences:"
          diff "$DEPS_FILE" "${DEPS_FILE}.new" || true
          echo ""
          
          mv "${DEPS_FILE}.new" "$DEPS_FILE"
          
          git checkout -B "$BRANCH_NAME"
          git add "$DEPS_FILE"
          
          if [ -f "requirements.in" ]; then
            git add requirements.in
          fi
          
          git commit -m "chore(deps): mise à jour automatique des dépendances Python

          Mises à jour effectuées par Dependabot
          Source EXCLUSIVE: Nexus PyPI
          URL: $NEXUS_PYPI_INDEX
          
          ✅ Toutes les dépendances proviennent de Nexus
          ✅ Aucune connexion à PyPI public
          ✅ Versions compatibles vérifiées"
          
          echo "⬆️ Push de la branche $BRANCH_NAME..."
          git push -f "https://oauth2:${GITLAB_TOKEN}@91.134.100.150/${CI_PROJECT_PATH}.git" "$BRANCH_NAME"
          
          echo "🔀 Création de la Merge Request..."
          MR_RESPONSE=$(curl -k -s --request POST "${GITLAB_API}/projects/${CI_PROJECT_ID}/merge_requests" \
            --header "PRIVATE-TOKEN: ${GITLAB_TOKEN}" \
            --header "Content-Type: application/json" \
            --data "{
              \"source_branch\": \"${BRANCH_NAME}\",
              \"target_branch\": \"main\",
              \"title\": \"🔄 Mise à jour automatique des dépendances Python (Nexus)\",
              \"description\": \"Cette MR contient les mises à jour automatiques des dépendances Python.\\n\\n### ✅ Source EXCLUSIVE\\n- Nexus PyPI: \`$NEXUS_PYPI_INDEX\`\\n- ❌ Aucune connexion à PyPI public\\n\\n### Changements\\n\\\`\\\`\\\`diff\\n$(diff ${DEPS_FILE}.old $DEPS_FILE | head -n 20)\\n\\\`\\\`\\\`\\n\\n**Note:** Vérifiez les tests avant de merger.\",
              \"remove_source_branch\": true,
              \"squash\": true
            }")
          
          echo "$MR_RESPONSE" | jq -r '.web_url // "❌ Erreur lors de la création de la MR"'
        else
          echo "✅ Aucune mise à jour disponible - $DEPS_FILE est déjà à jour avec les versions Nexus"
          rm -f "${DEPS_FILE}.new"
        fi
      else
        echo "⚠️ Fichier .new non généré - vérifiez les logs ci-dessus"
      fi
     
  rules:
    - when: always
  allow_failure: true

reset_runners:
  stage: cleanup
  tags:
    - runner-clean
  before_script:
    - apt update && apt install jq curl bash
  script:
    - chmod +x ./scripts/reset-runner.sh
    - ./scripts/reset-runner.sh
  when: always
  allow_failure: true
  only:
    - main