global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/rules/*.yml

scrape_configs:

  # Prometheus lui-même
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  # Machine (CPU, RAM, Disk, Network)
  - job_name: "node_exporter_machine"
    static_configs:
      - targets: ["IP_MACHINE:9100"]
        labels:
          team: "team"
          env: "linux"

  - job_name: "node_exporter_machine"
    static_configs:
      - targets: ["IP_MACHINE:9100"]
        labels:
          team: "team"
          env: "linux"

  - job_name: "node_exporter_machine"
    static_configs:
      - targets: ["IP_MACHINE:9100"]
        labels:
          team: "team"
          env: "linux"

  - job_name: "node_exporter_machine"
    static_configs:
      - targets: ["IP_MACHINE:9100"]
        labels:
          team: "team"
          env: "linux"

  - job_name: "node_exporter_machine"
    static_configs:
      - targets: ["IP_MACHINE:9100"]
        labels:
          team: "team"
          env: "linux"

  - job_name: "node_exporter_machine"
    static_configs:
      - targets: ["IP_MACHINE:9100"]
        labels:
          team: "team"
          env: "windows"

  - job_name: "node_exporter_machine"
    static_configs:
      - targets: ["IP_MACHINE:9100"]
        labels:
          team: "team"
          env: "windows"

  - job_name: "node_exporter_machine"
    static_configs:
      - targets: ["IP_MACHINE:9100"]
        labels:
          team: "team"
          env: "windows"

  - job_name: "node_exporter_machine"
    static_configs:
      - targets: ["IP_MACHINE:9100"]
        labels:
          team: "team"
          env: "windows"

  - job_name: "node_exporter_machine"
    static_configs:
      - targets: ["IP_MACHINE:9100"]
        labels:
          team: "team"
          env: "windows"

  - job_name: "node_exporter_machine"
    static_configs:
      - targets: ["IP_MACHINE:9100"]
        labels:
          team: "team"
          env: "windows"

  # Vérification UP / DOWN des dockers
  - job_name: "docker-custom-exporter"
    static_configs:
      - targets:
          - "IP_MACHINE:9101" # machine
          - "IP_MACHINE:9101" # machine
          - "IP_MACHINE:9101" # machine

  # Supervision BDD PostgreSQL
  - job_name: "postgres_exporter_machine"
    static_configs:
      - targets: ["IP_MACHINE:9187"]
        labels:
          team: "securite"

  # Supervision sites & certificats SSL / TLS
  - job_name: "blackbox_ssl"
    metrics_path: /probe
    params:
      module: [https_2xx]
    static_configs:
      - targets:
          - https://0.0.0.0:3000
        labels:
          service: "Service"
      - targets:
          - https://0.0.0.0:1443
        labels:
          service: "Service"
      - targets:
          - https://0.0.0.0
        labels:
          service: "Service"
      - targets:
          - https://0.0.0.0:8443
        labels:
          service: "Service"
      - targets:
          - https://0.0.0.0:3443
        labels:
          service: "Service"
      - targets:
          - https://0.0.0.0
        labels:
          service: "Service"
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: IP_MACHINE:9115
